AWSTemplateFormatVersion: "2010-09-09"

Resources: 
  trailMaster: 
    Type: "AWS::CloudTrail::Trail"
    Properties: 
      # TBD: How to specify the name of the trail
      S3BucketName: cle2wa-s3-trail-master
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true

