AWSTemplateFormatVersion: "2010-09-09"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: CrowdLabs EC2 Web Application Subaccount Base
        Parameters:
          - trailBucketName
          - groupName
          - userName
          - userPassword
          - userCliName
    ParameterLabels:
      trailBucketName:
        default: Name of shared S3 bucket for CloudTrail logs
      groupName:
        default: Admin Group Name
      userName:
        default: Admin Console User Name
      userPassword:
        default: Admin Console User Password
      userCliName:
        default: Admin CLI User Name

Parameters:
  trailBucketName:
    Type: String
    MinLength: 3
    MaxLength: 64
    Default: cle2wa-s3-trail-master
    AllowedPattern: ^[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]$
    ConstraintDescription: 3 to 64 upper case, lower case or dashes, must not start or end with a dash
  groupName:
    Type: String
    MinLength: 3
    MaxLength: 64
    Default: group-admin
    AllowedPattern: ^[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]$
    ConstraintDescription: 3 to 64 upper case, lower case or dashes, must not start or end with a dash
  userName:
    Type: String
    MinLength: 3
    MaxLength: 64
    Default: admin-console
    AllowedPattern: ^[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]$
    ConstraintDescription: 3 to 64 upper case, lower case or dashes, must not start or end with a dash
  userPassword:
    Description: Must conform to password policy
    Type: String
    MinLength: 8
    MaxLength: 32
    NoEcho: true
    ConstraintDescription: Password must be at least 8 characters
  userCliName:
    Type: String
    MinLength: 3
    MaxLength: 64
    Default: admin-cli
    AllowedPattern: ^[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]$
    ConstraintDescription: 3 to 64 upper case, lower case or dashes, must not start or end with a dash

Resources: 
  trailMaster: 
    Type: "AWS::CloudTrail::Trail"
    Properties: 
      # TBD: How to specify the name of the trail?
      S3BucketName: !Ref trailBucketName
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true

  adminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: group-admins
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess

  adminUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
      - !Ref adminGroup
      LoginProfile: 
        Password: !Ref userPassword
        PasswordResetRequired: false
      UserName: !Ref userName
      # Force MFA to be enable before most other things can be done
      Policies:
      - PolicyName: !Join ["", [!Ref groupName, "-policy"]]
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          -
            Sid: BlockAnyAccessOtherThanAboveUnlessSignedInWithMFA
            Effect: Deny
            NotAction: "iam:*"
            Resource: "*"
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: false

  adminCliUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
      - !Ref adminGroup
      UserName: !Ref userCliName